force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Membership</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/List_Price_Rate__c.field-meta.xml
<CustomField>
    <fullName>List_Price_Rate__c</fullName>
    <label>List Price Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ContactInformation.cls
public class ContactInformation { 
    @AuraEnabled
    public Customer customer;
    public ContactInformation(Contact c){
        list<PriceBookEntry> listOfPriceBookEntry=[Select Id, Name, CurrencyISOCode, Pricebook2.Name, Product2Id, Product2.Name, Product2.Family, UnitPrice, IsActive, UseStandardPrice, ProductCode, List_Price_Rate__c 
                                                   From PricebookEntry 
                                                   Where PriceBook2.Country__c=:c.Home_Country__c and Product2.Parent_Product__c = :c.Product__c and Product2.Family=:Constants.EXTRA_SERVICES];
        this.customer=new Customer(c.Name,c.Home_Country__c,c.Product__r.Name,listOfPriceBookEntry);
        
    }
    
    
}