force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Membership</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomerProductInformationController.cls
public class CustomerProductInformationController {
 @AuraEnabled 
    public static ContactInformation getCustomerProducts(string caseId){
        list<Contact> listOfContact=[Select Id,Name,Home_Country__c,Product__c,Product__r.Name from Contact where Home_Country__c!=null and Product__c!=null and Id in (Select ContactId from Case where Id=:caseId)];               
        if(listOfContact.size()==1)
        {
            return new ContactInformation(listOfContact[0]);           
        }
        else
            return null;
        
    } 
}